security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:clientId}
      client-secret: ${CLIENT_SECRET:client-secret}
      access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY:900}

server:
  error:
    whitelabel:
      enabled: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources.add-mappings: false
      
logging:
  level:
    org.springframework.web: INFO
    com.producer: INFO
    
  
kafka:
  bootstrapAddress: ${BOOTSTRAP_ADDRESS:localhost:9092}
  
message:
  topic:
    name: customer-queue
